apiVersion: apps/v1

kind: Deployment

metadata:
  name: second-app-deployment
  labels:
    group: example
spec:
  replicas: 1
  # This makes sure what pods should be controlled by the deployment based on the labels of the pods
  selector:
    matchLabels:
      app: second-app
    # matchExpressions:
    # - { key: app, operator: In, values: [second-app, first-app] }
    # - { key: app, operator: NotIn, values: [second-app, first-app] }

  # this is a pod
  template:
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      # one or multiple containers
      containers:
        - name: second-node
          image: grigoar/kub-first-app:2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              # httpHeaders:
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: second-node
        #   image:

