apiVersion: v1

kind: Service

metadata:
  name: backend
  labels:
    group: example

spec:
  # Selecting the pod with the labels desired
  selector:
    app: second-app
    # tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  # type: ClusterIP
  # type: NodeIP
  type: LoadBalancer

