apiVersion: v1
kind: Service
metadata:
  name: auth-service

spec:
  selector:
    app: auth
  # ? Not reachable from outside
  type: ClusterIP
  ports:
    - protocol: TCP
      # incomming requests
      port: 80
      # where the request will be forwarded (server is listening to 8080)
      targetPort: 80

