apiVersion: apps/v1
kind: Deployment

metadata:
  name: tasks-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: grigoar/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              # ? When multiple containers in the same pod can use localhost
              # value: localhost
              # value: '10.10.10.10'
              # ? can use the service name
              value: 'auth-service.default'
            - name: TASKS_FOLDER
              value: tasks
        # - name: auth
        #   image: grigoar/kub-demo-auth:latest

