apiVersion: v1
kind: Service
metadata:
  name: tasks-service

spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      # incomming requests
      port: 8000
      # where the request will be forwarded (server is listening to 8080)
      targetPort: 8000

