apiVersion: v1
kind: Service
metadata:
  name: users-service

spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      # incomming requests
      port: 8080
      # where the request will be forwarded (server is listening to 8080)
      targetPort: 8080

