apiVersion: apps/v1

kind: Deployment

metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: grigoar/kub-data-demo:2
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
          env:
            - name: STORY_FOLDER
              # value: 'story'
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
      volumes:
        - name: story-volume
          # ? This is used only for pods ( when using replicas might fail)
          # emptyDir: {}
          # ? this search for a path on the host machine ( it also can read already existing code in that file)
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          # ? access the persistent storage by claim
          persistentVolumeClaim:
            claimName: host-pvc

